[api]
url = http://127.0.0.1:8000
mcp = yes

[list_exitnodes]
enabled = yes
mcp = yes

[statistics]
enabled = yes
mcp = yes

[download_file]
mcp = yes

[filereport]
mcp = yes

[dlnexeccreate]
enabled = yes
mcp = yes

[staticextraction]
mcp = yes

[filecreate]
mcp = yes

[urlcreate]
mcp = yes

[downloading_services]
enabled = yes
mcp = yes

[fileview]
mcp = yes

[web_search]
mcp = yes

[tasksearch]
mcp = yes

[extendedtasksearch]
mcp = yes

[tasklist]
mcp = yes

[taskview]
mcp = yes

[taskresched]
enabled = yes
mcp = yes

[taskreprocess]
enabled = yes
mcp = yes

[taskdelete]
enabled = yes
mcp = yes

[taskstatus]
mcp = yes

[taskreport]
mcp = yes

[taskiocs]
mcp = yes

[taskscreenshot]
mcp = yes

[taskpcap]
mcp = yes

[tasktlspcap]
mcp = yes

[taskevtx]
mcp = yes

[tasktlskeys]
mcp = yes

[tasketw]
mcp = yes

[taskbulkzip]
mcp = yes

[taskdropped]
mcp = yes

[taskselfextracted]
enabled = yes
mcp = yes

[tasksurifile]
mcp = yes

[taskprocdump]
mcp = yes

[taskprocmemory]
mcp = yes

[taskfullmemory]
enabled = yes
mcp = yes

[taskmitmdump]
enabled = yes
mcp = yes

[sampledl]
enabled = yes
mcp = yes

[machinelist]
enabled = yes
mcp = yes

[machineview]
enabled = yes
mcp = yes

[cuckoostatus]
enabled = yes
mcp = yes

[rollingsuri]
enabled = yes
mcp = yes

[rollingshrike]
enabled = yes
mcp = yes

[capeconfig]
auth_only = no
mcp = yes

[procdumpfiles]
enabled = yes
mcp = yes

[payloadfiles]
mcp = yes

[tasks_latest]
enabled = yes
mcp = yes

[task_x_hours]
enabled = yes
mcp = yes

[full_memory_dump_file]
enabled = yes
mcp = yes

[full_memory_dump_file_strings]
enabled = yes
mcp = yes

[comments]
enabled = yes
mcp = yes

[yara_uploader]
enabled = yes
mcp = yes

[user_stop]
enabled = yes
mcp = yes

[mitmdump]
enabled = yes
mcp = yes