[downloading_services]
enabled = yes

[taskreprocess]
enabled = yes

[taskselfextracted]
enabled = yes

[taskfullmemory]
enabled = yes

[taskmitmdump]
enabled = yes

[sampledl]
enabled = yes

[machinelist]
enabled = yes

[machineview]
enabled = yes

[cuckoostatus]
enabled = yes

[procdumpfiles]
enabled = yes

[tasks_latest]
enabled = yes

[task_x_hours]
enabled = yes

[full_memory_dump_file]
enabled = yes

[full_memory_dump_file_strings]
enabled = yes

[comments]
enabled = yes

[yara_uploader]
enabled = yes

[user_stop]
enabled = yes

[mitmdump]
enabled = yes